version = 0.1
[default.deploy.parameters]
stack_name = "Project-Sprint6-Group3"
resolve_s3 = true
s3_prefix = "Project-Sprint6-Group3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ElasticsearchDomainName=\"voiceptlanguage\" SourceAudioLanguage=\"pt-BR\""
image_repositories = []
